# from automata.fa.Moore import Moore
from automata.fa.Moore import Moore
import sys, os
import string
from collections import defaultdict
import xml.etree.ElementTree as ET
from xml.dom import minidom
from myerror import MyError

error_handler = MyError('LexerErrors')

global check_cm
global check_key

alfabeto = list(string.ascii_lowercase + string.ascii_uppercase)

numeros = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']

caracter = ['\n', ' ', '(', ')', '[', ']', '{', '}', ';', ',', '+', '-', '/', '*', '=', '!', '<', '>']

fullList = alfabeto + numeros + caracter

##estados##

states = ['q0','qId', 'qId1', 'qNum', 'qNum1', 'qF', 'qL1', 'qO', 'qA', 'qT', 'qIF', 'qIF1', 'q_else1', 'q_else2', 'q_else3', 'q_else4', 'q_int1', 'q_int2', 'q_int3', 'q_int4', 'q_return1', 'q_return2', 'q_return3', 'q_return4', 'q_return5', 'q_return6',
'q_void1', 'q_void2', 'q_void3', 'q_void4', 'qW','qH','qI', 'qL', 'qE', 'qPlus', 'qMinus', 'qVezes', 'qDivide', 'qLess', 'qLessEqual', 'qMaior', 'qMaiorIgual', 'qIgual',
 'qDiferent', 'qDParenteses', 'qEParenteses', 'qDColchete', 'qEColchete', 'qDChaves', 'qEChaves', 'qIgualIgual', 'qPontoVirgula', 'qPonto',
 'qDiferent1']

##labels##

labels = ['INT', 'IF', 'ELSE', 'VOID', 'RETURN', 'WHILE', 'FLOAT,', 'MINUS', 'PLUS', 'TIMES', 'DIVIDE', 'LESS', 'LESS_EQUAL',
    'GREATER_EQUAL', 'GREATER', 'EQUALS', 'DIFFERENT', 'LPAREN', 'RPAREN', 'LBRACKETS', 'RBRACKETS', 'LBRACES', 'RBRACES',
    'ATTRIBUTION', 'SEMICOLON', 'COMMA', 'NUMERO', ' ID ']

##transicoes##
transitions = {
     'q0': {
                'i': 'q_int1',
                'e': 'q_else1',
                'f': 'qF',
                'r': 'q_return1',
                'v': 'q_void1',
                'w': 'qW',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            id : {
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_int1' : {
                'f' : 'qIF',
                'n' : 'q_int2',
                ##misc##
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\n' : 'q0',
                ' ' : 'qId',
                '\t' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qIF' : {
                #fim do if#
               '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_int2' : {
                't' : 'q_int3',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_int3' : {
              ## fim do int ##  
               '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_else1' : {
                'l' : 'q_else2',
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_else2' : {
                's' : 'q_else3',
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_else3' : {
                'e' : 'q_else4',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_else4' : {
                ## fim do else ##
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_return1' : {
                'e' : 'q_return2',
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_return2' : {
                't' : 'q_return3',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_return3' : {
                'u' : 'q_return4',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_return4' : {
                'r': 'q_return5',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_return5' : {
                'n': 'q_return6',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_return6' : {
                #fim do return#
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_void1': {
                'o': 'q_void2',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_void2' : {
                'i': 'q_void3',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_void3' : {
                'd' : 'q_void4',
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'q_void4' : {
                ##fim do void ##
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qW' : {
                'h': 'qH',
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qH' : {
                'i': 'qI',
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qI' : {
                'l': 'qL',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qL' : {
                'e' : 'qE',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qE' : {
                ## fim do while ##
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qF' : {
                'l' : 'qL1',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qL1' : {
                'o': 'qO',
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qO' : {
                'a' : 'qA',
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qA' : {
                't' : 'qT',
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qT' : { 
                ## fim do float##
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qMinus' : {
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qPlus' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qVezes' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qDivide' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qLess' : {
                '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=':  'qLessEqual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qLessEqual' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qMaior' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qMaiorIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qMaiorIgual' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qIgual' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgualIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qIgualIgual' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qDiferent' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qDiferent1',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qDiferent1' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qDParenteses' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qEParenteses' : {
                                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qEChaves' : {
                                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qDChaves' : {
                                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            }, 
            'qDColchete' : {
                                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qEColchete' : {
                                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qPontoVirgula' : {
                                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qPonto' : {
                                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qId' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId1',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qId1' : {
            ## fim do ID
             '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qNum' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qNum1',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            },
            'qNum1' : {
                 '+': 'qPlus',
                '-': 'qMinus',
                '*': 'qVezes',
                '/': 'qDivide',
                '<': 'qLess',
                '>': 'qMaior',
                '=': 'qIgual',
                '!': 'qDiferent',
                '(': 'qDParenteses',
                ')': 'qEParenteses',
                '[': 'qDColchete',
                ']': 'qEColchete',
                '{': 'qDChaves',
                '}': 'qEChaves',
                ';': 'qPontoVirgula',
                ',': 'qPonto',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNum',,
                '2' : 'qNum',
                '3' : 'qNum',
                '4' : 'qNum',
                '5' : 'qNum',
                '6' : 'qNum',
                '7' : 'qNum',
                '8' : 'qNum',
                '9' : 'qNum',
                '0' : 'qNum',
            }
}

initial_state = "q0"

tabela_saida = {
    'q0'  : '',
    'qId' : '',
    'qId1' : 'ID\n', 
    'qNum' : '',
    'qNum1' : 'NUMERO\n',
    'qF' : '',
    'qL1' : '',
    'qO' : '',
    'qA' : '',
    'qT' : 'FLOAT\n',
    'qIF' : '',
    'qIF1' : 'IF\n', 
    'q_else1' : '',
    'q_else2' : '',
    'q_else3' : '',
    'q_else4' : 'ELSE\n',
    'q_int1' : '',
    'q_int2' : '',
    'q_int3' : 'INT\n',
    'q_return1' : '',
    'q_return2' : '',
    'q_return3' : '',
    'q_return4' : '', 
    'q_return5' : '', 
    'q_return6' : 'RETURN\n',
    'q_void1' : '',
    'q_void2' : '',
    'q_void3' : '',
    'q_void4' : 'VOID\n',
    'qW' : '',
    'qH' : '',
    'qI' : '',
    'qL' : '',
    'qE' : 'WHILE\n',
    'qPlus' : 'PLUS\n',
    'qMinus' : 'MINUS\n', 
    'qVezes' : 'VEZES\n', 
    'qDivide' : 'DIVIDE\n',
    'qLess' : 'LESS\n',
    'qLessEqual' : 'LESS_EQUAL\n', 
    'qMaior' : 'GREATER\n', 
    'qMaiorIgual' : 'GREATER_EQUAL\n', 
    'qIgual' : 'ATTRIBUTION\n',
    'qDiferent' : '',
    'qDParenteses' : 'LPAREN\n', 
    'qEParenteses' : 'RPAREN\n',
    'qDColchete' : 'LBRACKETS\n',
    'qEColchete' : 'RBRACKETS\n', 
    'qDChaves' : 'LBRACES\n', 
    'qEChaves' : 'RBRACES\n',
    'qIgualIgual' : 'EQUALS\n',
    'qPontoVirgula' : 'SEMICOLON\n', 
    'qPonto' : 'COMMA\n',
    'qDiferent1': 'DIFFERENT\n'
}
moore = Moore(
    states,
    fullList,
    labels,
    transitions,
    initial_state = initial_state,
    tabela_saida = tabela_saida
)

def main():
    check_cm = False
    check_key = False
    
    for idx, arg in enumerate(sys.argv):
        aux = arg.split('.')
        if aux[-1] == 'cm':
            check_cm = True
            idx_cm = idx

        if arg == "-k":
            check_key = True

    if check_key:
        if len(sys.argv) < 3:
            raise TypeError(error_handler.newError(check_key, 'ERR-LEX-USE'))
    else:
        if len(sys.argv) < 2:
            raise TypeError(error_handler.newError(check_key, 'ERR-LEX-USE'))
        
    if not check_cm:
        raise IOError(error_handler.newError(check_key, 'ERR-LEX-NOT-CM'))
    
    if not os.path.exists(sys.argv[idx_cm]):
        raise IOError(error_handler.newError(check_key, 'ERR-LEX-FILE-NOT-EXISTS'))

    else:
        # Print da configuração do automato caso check_key não é verdadeiro
        if (not check_key):
            print(  states,
                    fullList,
                    labels,
                    transitions,
                    initial_state,
                    tabela_saida )


        data = open(sys.argv[idx_cm])
        source_file = data.read()
        data.close()  # Fecha o arquivo após a leitura

        if not check_cm:
            print("Definição da Máquina")
            print(moore)
            print("Entrada:")
            print(source_file)
            print("Lista de Tokens:")

        try:
            output = moore.get_output_from_string(source_file)
            print(output)  # Se não houver erro, imprime os tokens normalmente
        except ValueError as e:  # Se detectar um caractere inválido
            raise ValueError(error_handler.newError(check_key, 'ERR-LEX-INV-CHAR'))


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e)
    except (ValueError, TypeError) as e:
        print(f"Erro de valor ou tipo: {e}")
